---
abstract: 'Process payments through JSON API of Suomen Verkkomaksut in Finland. Enables payments from all Finnish Banks online: Nordea, Osuuspankki, Sampo, Tapiola, Aktia, Nooa, Paikallisosuuspankit, Säästöpankit, Handelsbanken, S-Pankki, Ålandsbanken, also from Visa, Visa Electron, MasterCard credit cards through Luottokunta, and PayPal, billing through Collector and Klarna.'
author:
  - 'Oskari Okko Ojala <okko@cpan.org>, Frantic Oy http://www.frantic.com/'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Bank-SuomenVerkkomaksut
requires:
  Data::Dumper: 0
  Digest::MD5: 0
  JSON::XS: 0
  Moose: 0
  Net::SSLeay: 0
  utf8: 0
resources:
  repository: git://github.com/okko/Finance-Bank-SuomenVerkkomaksut.git
version: 0.003
x_authority: cpan:OKKO
